[theme]
name = "semi-native"

[theme.overrides]

[icons]
name = "material-nf"

[icons.overrides]
cpu = ""
memory_mem = ""
pomodoro = ""
thermometer = ""
net_up = "&gt;"
net_down = "&lt;"
weather_rain = " "
weather_sun = " "
weather_clouds = " "
time = " "
net_wired = "省"
cogs = ""

[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"

[[block]]
block = "custom"
command = 'xkblayout-state print %s'
interval = 5

[[block]]
block = "custom"
command = '/home/chris/bin/mixbus_version_check'
interval = 120

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " {percentage}"
alert_absolute = true
unit = "GB"
alert = 50
warning = 40

[[block]]
block = "disk_space"
path = "/home/chris/bck"
info_type = "available"
format = " {percentage}"
alert_absolute = true
unit = "GB"
alert = 2
warning = 10

[[block]]
block = "net"
device = "enp39s0"
format = "{speed_up;M*b} {speed_down;M*b}"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}"
clickable = false
icons = true


[[block]]
block = "custom"
command = "~/bin/get_gov"
on_click = "~/bin/toggle_gov"
interval = 5

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "load"
format = " {1m}"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "zenpower-pci-00c3"
inputs = ["Tdie"]

#on_click = "alacritty --title='Weather' -e ~/bin/aweather"

[[block]]
block = "weather"
format = "{weather_verbose} {temp}"
service = { name = "openweathermap", api_key = "dbd42c1d415c1e8e51790ede79cbd258", city_id = "2911298", units = "metric" }
interval = 60

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %H:%M"
on_click = "alacritty --title='Calendar' -e ~/bin/kcal"
